config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: "homes#top"
  get 'home/about' => 'homes#about', as:'about'

  resources :books, onlt: [:new, :create, :index, :show, :edit, :update, :destory]
  resources :users, only: [:new, :index, :show, :edit, :update]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  
  belongs_to :user
  has_one_attached :profile_image
  
  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: { maximum: 200 }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_login_user, only: [:edit]

  def new
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id

    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end


  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def show
    @books = Book.all
    @book = Book.find(params[:id])
    @user = @book.user
    @book_ = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

   def book_params
     params.require(:book).permit(:title, :body)
   end

   def is_matching_login_user
     book = Book.find(params[:id])
     user = book.user
     unless user.id == current_user.id
       redirect_to books_path
     end
   end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_list.html.erb
    <div class="col-md-3">
      <h2>User info</h2>

          <% if user.profile_image.attached? %>
            <%= image_tag user.profile_image, size: "100x100" %>
          <% else %>
            <%= image_tag 'no_image', size: "100x100" %>
          <% end %>

          <table class="table table-striped">
            <tbody>
              <tr>
                <th>name</th>
                <td><%= user.name %></td>
              </tr>
              <tr>
                <th>introduction</th>
                <td><%= user.introduction %></td>
              </tr>
            </tbody>
          </table>

        <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
        <i class="fa-solid fa-user-gear" style="color: #5a5f67;"></i>
        <% end %>

      <h2>New book</h2>
        <%= form_with model: book do |f| %>
          <h4>Title</h4>
          <%= f.text_field :title %>
          <h4>Opinion</h4>
          <%= f.text_area :body %>
          <br>
          <div class="col-6">
          <%= f.submit 'Create Book', class: "btn btn-success btn-sm btn-block" %>
          </div>
        <% end %>
    </div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-5 px-5 mx-auto">


<h1>Editing Book</h1>

<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %>
      </li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book do |f| %>

  <label for="inputTitle">Title</label><br>
  <%= f.text_field :title, autofocus: true, id:"inputTitle", placeholder:"Title" %><br><br>

  <label for="inputBody">Opinion</label><br>
  <%= f.text_area :body, autofocus: true %><br><br>

  <div class="btn-wrapper col-5">
  <%= f.submit "Update Book", class: "btn btn-success btn-sm btn-block" %>
  </div>
  <% end %>


  <%= link_to "Show", book_path(@book.id) %>
  |
  <%= link_to "Back", "/books" %>

    </div>
  </div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %>
      </li>
    <% end %>
  </ul>
<% end %>
<div class="container">
<div class="row">
<%= render 'list', book: @book, user: @user %>
    

<div class="col-md-8 offset-md-1">
<table class="table table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
    </tr>
  </thead>

  <tbody>
    <h2>Books</h2>
    <% @books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user) do %>
            <%= image_tag book.user.get_profile_image(100,100) %>
            <% end %>
        </td>
        <td><%= link_to book_path(book) do %>
              <%=book.title %>
            <% end %>
        </td>
        <td><%= book.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
</div>

app/views/books/new.html.erb
<div>
  <%= flash[:notice] %>
</div>

<%= render 'list', books: @books %>

<div class="offset-md-1"></div>
<div class="col-md-8">
<table class="table table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
    </tr>
  </thead>

  <tbody>
    <h2>Books new</h2>
    <% @books.each do |book| %>
      <tr>
        <td><%= image_tag book.user.get_profile_image(100,100) %></td>
        <td><%= book.title %></td>
        <td><%= book.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
</div>

app/views/books/show.html.erb
<div class="container">
<div class="row">

<%= render 'list', book: Book.new, user: @user %>

<div class="col-md-8 offset-md-1">

<table class="table table-striped">


  <tbody>
    <h2>Book detail</h2>
        <tr>

          <td><%= link_to user_path(@user) do %>
              <%= image_tag @user.get_profile_image(100,100) %><br>
              <%= @user.name %>
              <% end %>
          </td>

          <td><%=link_to book_path(@book) do %>
                <%= @book.title %>
              <% end %>
          </td>
          <td><%= @book.body %></td>

          <% if @user == current_user %>
            <div class="btn-wrapper col-1 mx-auto">
              <td><%= link_to "Edit", edit_book_path(@book), class: "btn btn-success btn-sm btn-block" %></td>
              <td><%= link_to "Destroy", book_path(@book), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-sm btn-block" %></td>
            </div>
          <% end %>
        </tr>
  </tbody>
</table>
</div>
</div>
</div>