config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: "homes#top"
  get 'home/about' => 'homes#about', as:'about'

  resources :books, onlt: [:new, :create, :index, :show, :edit, :update, :destory]
  resources :users, only: [:new, :index, :show, :edit, :update]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

   <script src="https://kit.fontawesome.com/012172cb3f.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" date-toggle="collapse" date-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">

            <% if user_signed_in? %>

            <li class="nav-item">
              <%= link_to user_path(current_user), class: 'nav-link text-light link-opacity-10-hover' do %>
                <i class="fa-solid fa-house" style="color: #ffffff;"></i>
                Home
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to users_path, class: 'nav-link text-light' do %>
                <i class="fa-solid fa-users" style="color: #ffffff;"></i>
                Users
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to books_path, class: 'nav-link text-light' do %>
                <i class="fa-solid fa-book-open" style="color: #ffffff;"></i>
                Books
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
                <i class="fa-solid fa-right-from-bracket" style="color: #ffffff;"></i>
                Log out
              <% end %>
            </li>

          <% else %>

            <li class="nav-item">
              <%= link_to root_path, class: 'nav-link text-light' do %>
                <i class="fa-solid fa-house" style="color: #ffffff;"></i>
                Home
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to about_path, class: 'nav-link text-light' do %>
                <i class="fa-solid fa-link" style="color: #ffffff;"></i>
                About
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
                <i class="fa-solid fa-user-plus" style="color: #ffffff;"></i>
                Sign up
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
                <i class="fa-solid fa-right-to-bracket" style="color: #ffffff;"></i>
                Log in
              <% end %>
            </li>

          <% end %>

            </ul>
          </div>
        </div>
      </nav>
    </header>


    <main class="mb-auto">
      <p class="notice"><%= notice %></p>
    <%= yield %>
    </main>
    <footer class="text-dark pt-5 pb-4">
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
     </footer>
  </body>
</html>